create table if not exists public.web_analytics_page_views (
  id bigint generated by default as identity primary key,
  session_hash text not null,
  path_group text not null,
  device_category text not null default 'unknown' check (
    device_category in ('mobile', 'tablet', 'desktop', 'unknown')
  ),
  created_at timestamptz not null default now(),
  check (session_hash ~ '^[0-9a-f]{64}$'),
  check (char_length(path_group) between 1 and 160),
  check (path_group like '/%')
);

create index if not exists web_analytics_page_views_created_idx
on public.web_analytics_page_views(created_at desc);

create index if not exists web_analytics_page_views_path_created_idx
on public.web_analytics_page_views(path_group, created_at desc);

create index if not exists web_analytics_page_views_session_created_idx
on public.web_analytics_page_views(session_hash, created_at desc);

alter table public.web_analytics_page_views enable row level security;

-- Browser roles never access raw analytics rows. The validated server route
-- writes page views and the administrator-only API reads aggregate RPC output.
revoke all on table public.web_analytics_page_views from anon, authenticated;
grant select, insert, delete on table public.web_analytics_page_views to service_role;
grant usage, select on sequence public.web_analytics_page_views_id_seq to service_role;

create or replace function public.prune_web_analytics_page_views()
returns bigint
language plpgsql
security invoker
set search_path = public
as $function$
declare
  deleted_rows bigint;
begin
  with deleted as (
    delete from public.web_analytics_page_views
    where created_at < now() - interval '90 days'
    returning 1
  )
  select count(*) into deleted_rows from deleted;

  return deleted_rows;
end;
$function$;

revoke all on function public.prune_web_analytics_page_views() from public, anon, authenticated;
grant execute on function public.prune_web_analytics_page_views() to service_role;

create or replace function public.get_web_analytics_summary(p_days integer default 30)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $function$
with normalized as (
  select
    least(90, greatest(7, coalesce(p_days, 30)))::integer as range_days,
    date_trunc('day', timezone('Asia/Tokyo', now())) as today_jst
),
bounds as (
  select
    range_days,
    today_jst,
    timezone(
      'Asia/Tokyo',
      today_jst - ((range_days - 1)::text || ' days')::interval
    ) as starts_at,
    timezone('Asia/Tokyo', today_jst + interval '1 day') as ends_at,
    timezone('Asia/Tokyo', today_jst) as today_starts_at
  from normalized
),
filtered as (
  select page_view.*
  from public.web_analytics_page_views page_view
  cross join bounds
  where page_view.created_at >= bounds.starts_at
    and page_view.created_at < bounds.ends_at
    and page_view.path_group not like '/admin%'
),
totals as (
  select
    count(*)::bigint as page_views,
    count(distinct session_hash)::bigint as sessions
  from filtered
),
today_totals as (
  select
    count(*)::bigint as page_views,
    count(distinct filtered.session_hash)::bigint as sessions
  from filtered
  cross join bounds
  where filtered.created_at >= bounds.today_starts_at
),
session_counts as (
  select session_hash, count(*)::bigint as page_views
  from filtered
  group by session_hash
),
session_metrics as (
  select count(*) filter (where page_views = 1)::bigint as single_page_sessions
  from session_counts
),
daily_series as (
  select generate_series(
    normalized.today_jst - ((normalized.range_days - 1)::text || ' days')::interval,
    normalized.today_jst,
    interval '1 day'
  )::date as day
  from normalized
),
daily_counts as (
  select
    timezone('Asia/Tokyo', created_at)::date as day,
    count(*)::bigint as page_views,
    count(distinct session_hash)::bigint as sessions
  from filtered
  group by timezone('Asia/Tokyo', created_at)::date
),
top_pages as (
  select
    path_group,
    count(*)::bigint as page_views,
    count(distinct session_hash)::bigint as sessions
  from filtered
  group by path_group
  order by page_views desc, path_group asc
  limit 15
),
device_counts as (
  select
    device_category,
    count(*)::bigint as page_views,
    count(distinct session_hash)::bigint as sessions
  from filtered
  group by device_category
  order by page_views desc, device_category asc
),
recent_views as (
  select path_group, device_category, created_at
  from filtered
  order by created_at desc
  limit 15
),
collection_window as (
  select
    min(created_at) as collected_since,
    max(created_at) as last_received_at
  from public.web_analytics_page_views
  where path_group not like '/admin%'
)
select jsonb_build_object(
  'rangeDays', bounds.range_days,
  'startsAt', bounds.starts_at,
  'endsAt', bounds.ends_at,
  'pageViews', totals.page_views,
  'sessions', totals.sessions,
  'pagesPerSession', case
    when totals.sessions = 0 then 0
    else round(totals.page_views::numeric / totals.sessions::numeric, 2)
  end,
  'singlePageRate', case
    when totals.sessions = 0 then 0
    else round(
      session_metrics.single_page_sessions::numeric * 100 / totals.sessions::numeric,
      1
    )
  end,
  'todayPageViews', today_totals.page_views,
  'todaySessions', today_totals.sessions,
  'collectedSince', collection_window.collected_since,
  'lastReceivedAt', collection_window.last_received_at,
  'daily', coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'day', daily_series.day,
        'pageViews', coalesce(daily_counts.page_views, 0),
        'sessions', coalesce(daily_counts.sessions, 0)
      )
      order by daily_series.day
    )
    from daily_series
    left join daily_counts on daily_counts.day = daily_series.day
  ), '[]'::jsonb),
  'topPages', coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'pathGroup', top_pages.path_group,
        'pageViews', top_pages.page_views,
        'sessions', top_pages.sessions
      )
      order by top_pages.page_views desc, top_pages.path_group asc
    )
    from top_pages
  ), '[]'::jsonb),
  'devices', coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'deviceCategory', device_counts.device_category,
        'pageViews', device_counts.page_views,
        'sessions', device_counts.sessions
      )
      order by device_counts.page_views desc, device_counts.device_category asc
    )
    from device_counts
  ), '[]'::jsonb),
  'recent', coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'pathGroup', recent_views.path_group,
        'deviceCategory', recent_views.device_category,
        'createdAt', recent_views.created_at
      )
      order by recent_views.created_at desc
    )
    from recent_views
  ), '[]'::jsonb)
)
from bounds
cross join totals
cross join today_totals
cross join session_metrics
cross join collection_window;
$function$;

revoke all on function public.get_web_analytics_summary(integer) from public, anon, authenticated;
grant execute on function public.get_web_analytics_summary(integer) to service_role;
